[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"

[phases.setup]
nixPkgs = [
    "nodejs_20",
    "chromium"
]

[phases.install]
cmds = [
    "npm ci --only=production --no-audit --no-fund"
]

[start]
cmd = "npm start"
