[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"

[phases.setup]
nixPkgs = [
    "nodejs_18",
    "google-chrome"
]

[phases.install]
cmds = [
    "npm ci --only=production --no-audit --no-fund"
]

[start]
cmd = "npm start"
